service: my-rest-api

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 10
  stage: dev
  region: us-east-1

functions:
  authorise: 
    handler: services/auth/handler.isUserAuthorised

  create:
    handler: services/film/handler.create
    events: 
      - http:
          path: film
          method: post
          cors: true
          authorizer: authorise

  getFilm:
    handler: services/film/handler.getFilm
    events:
      - http:
          path: film/{title}
          method: get
          cors: true

  getFilms:
    handler: services/film/handler.getFilms
    events:
      - http:
          path: films
          method: get
          cors: true

  update:
    handler: services/film/handler.update
    events:
      - http:
          path: film/{id}
          method: put
          cors: true
          authorizer: authorise

  delete:
    handler: services/film/handler.delete
    events:
      - http:
          path: film/{id}
          method: delete
          cors: true
          authorizer: authorise

# AUTH CONTROLS --------------------------------------
  getUserList:
    handler: services/auth/handler.getUsers
    events:
        - http:
            path: users
            method: get
            cors: true
            authorizer: authorise

  register:
    handler: services/auth/handler.register
    events:
      - http:
          path: register
          method: post
          cors: true

  login:
    handler: services/auth/handler.login
    events:
      - http:
          path: login
          method: post
          cors: true

  updatePassword:
    handler: services/auth/handler.updateUserPassword
    events:
      - http:
          path: updatepassword
          method: update
          cors: true

  deleteUser:
    handler: services/auth/handler.deleteUser
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true
          authorizer: authorise

# Blog Endpoints -------------------------------------

getBlogs:
  handler: services/blog/handler.getBlogs
  events:
    - http:
        path: blog
        method: get
        cors: true

getBlog:
  handler: services/blog/handler.getBlog
    - http:
        path: blog/{slug}
        method: get
        cors: true

createBlog:
  handler: services/blog/handler.createBlog
    - http:
        path: blog
        method: post
        cors: true
        authorizer: authorise

deleteBlog:
  handler: services/blog/handler.deleteBlog
  - http:
      path: blog/{id}
      method: delete
      cors: true
      authorizer: authorise

plugins:
- serverless-offline # adding the plugin to be able to run the offline emulation