service: my-rest-api

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 10
  stage: dev
  region: us-east-1

functions:
  create:
    handler: handler.create
    events: 
      - http:
          path: film
          method: post
          cors: true

  getFilm:
    handler: handler.getFilm
    events:
      - http:
          path: film/{title}
          method: get
          cors: true

  getFilms:
    handler: handler.getFilms
    events:
      - http:
          path: films
          method: get
          cors: true

  update:
    handler: handler.update
    events:
      - http:
          path: film/{id}
          method: put
          cors: true

  delete:
    handler: handler.delete
    events:
      - http:
          path: film/{id}
          method: delete
          cors: true

plugins:
- serverless-offline # adding the plugin to be able to run the offline emulation